CREATE TABLE `program_radio_playbill` (
                                          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                                          `uin` int(11) unsigned NOT NULL DEFAULT '0',
                                          `channelId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '频道id',
                                          `name` varchar(15) NOT NULL DEFAULT '' COMMENT '节目名称',
                                          `type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0自动1手动设置',
                                          `week` tinyint(1) NOT NULL COMMENT '周一-周日0-6',
                                          `mssUrl` varchar(255) DEFAULT NULL COMMENT '媒资url',
                                          `startTime` char(8) NOT NULL DEFAULT '00:00:00' COMMENT '开始时间',
                                          `endTime` char(8) NOT NULL DEFAULT '00:00:00' COMMENT '结束时间',
                                          `sTaskId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '开始计划任务ID',
                                          `eTaskId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '结束计划任务ID',
                                          `mTaskId` int(11) unsigned DEFAULT NULL COMMENT '合并id',
                                          `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '1删除0正常',
                                          `deleteTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '删除时间',
                                          `createTime` int(11) NOT NULL COMMENT '创建时间',
                                          `updateTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
                                          PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=6783 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `program_tv_playbill` (
                                       `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                                       `uin` int(11) unsigned NOT NULL DEFAULT '0',
                                       `channelId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '频道id',
                                       `name` varchar(15) NOT NULL DEFAULT '' COMMENT '节目名称',
                                       `type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0自动1手动设置',
                                       `week` tinyint(1) NOT NULL COMMENT '周一-周日0-6',
                                       `mssUrl` varchar(255) DEFAULT NULL COMMENT '媒资url',
                                       `startTime` char(8) NOT NULL DEFAULT '00:00:00' COMMENT '开始时间',
                                       `endTime` char(8) NOT NULL DEFAULT '00:00:00' COMMENT '结束时间',
                                       `sTaskId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '开始计划任务ID',
                                       `eTaskId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '结束计划任务ID',
                                       `mTaskId` int(11) unsigned DEFAULT NULL COMMENT '合并id',
                                       `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '1删除0正常',
                                       `deleteTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '删除时间',
                                       `createTime` int(11) NOT NULL COMMENT '创建时间',
                                       `updateTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
                                       PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2590 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `program_tv_channel` (
                                      `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                                      `name` varchar(180) NOT NULL DEFAULT '' COMMENT '名称',
                                      `introduce` varchar(50) NOT NULL DEFAULT '' COMMENT '简介',
                                      `logo` varchar(50) NOT NULL COMMENT '聚合页logo',
                                      `mpsBackground` varchar(64) NOT NULL DEFAULT '' COMMENT '²¥·Å±³¾°Í¼',
                                      `mpsLssAppId` varchar(20) NOT NULL DEFAULT '' COMMENT '播放器实例id',
                                      `mpsDynamicVodAppId` varchar(20) NOT NULL DEFAULT '' COMMENT 'mps 动态点播实例id',
                                      `status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '状态1正常2回收站',
                                      `uin` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '操作人',
                                      `childId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '子账号id-0主账号',
                                      `aid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '频道id',
                                      `playlistsStatus` tinyint(1) unsigned NOT NULL DEFAULT '2' COMMENT 'µã²¥Ä£°å×´Ì¬1ÆôÓÃ2¹Ø±Õ',
                                      `playlistsId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'µã²¥Ä£°åid',
                                      `createTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
                                      `updateTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '修改时间',
                                      `pullUrl` varchar(1000) NOT NULL DEFAULT '' COMMENT 'À­Á÷µØÖ·',
                                      `pullStatus` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'À­Á÷µØÖ·ÊÇ·ñÆôÓÃ£¨0¹Ø±Õ£¬1ÆôÓÃ£©',
                                      `publishTaskId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '·¢²¼ÈÎÎñid',
                                      `publishTaskMakeAppId` varchar(20) NOT NULL DEFAULT '' COMMENT '·¢²¼ÈÎÎñ°ó¶¨µÄÖÆ×÷µ¼²¥Ì¨ÊµÀýid',
                                      `chatAuthModel` tinyint(1) unsigned NOT NULL DEFAULT '2' COMMENT 'ÁÄÌìÉóºËÀàÐÍ1£ºÖðÌõÉóºË2Ãô¸ÐÉóºË3×Ô¶¯¹ýÂË',
                                      `chatLogin` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'ÁÄÌìÊÇ·ñÐèÒªµÇÂ¼£¬1ÐèÒª0²»ÐèÒª',
                                      `chatAdminName` varchar(20) NOT NULL DEFAULT '' COMMENT 'ÁÄÌì¹ÜÀíÔ±Ãû',
                                      `chatSee` tinyint(1) NOT NULL DEFAULT '1',
                                      `chatAdminAva` varchar(64) NOT NULL DEFAULT '' COMMENT 'ÁÄÌì¹ÜÀíÔ±Í·Ïñ',
                                      `defaultUserAva` varchar(64) NOT NULL DEFAULT '',
                                      `pullStream` int(1) unsigned NOT NULL DEFAULT '0' COMMENT 'ÊÇ·ñÀ­Á÷ 1ÊÇ 0·ñ',
                                      `lssApp` varchar(64) NOT NULL DEFAULT '' COMMENT 'lss APP',
                                      `stream` varchar(64) NOT NULL DEFAULT '' COMMENT '流stream',
                                      `watchNum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '观看数量',
                                      `customWatchStatus` tinyint(1) unsigned NOT NULL DEFAULT '2' COMMENT '是否开启自定义观看数据，2否1是',
                                      `isDisplayWatchNum` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否展示观看量1是2否',
                                      `streamType` tinyint(1) unsigned NOT NULL DEFAULT '1',
                                      `shareImg` varchar(64) NOT NULL,
                                      `shareSubTitle` varchar(200) NOT NULL,
                                      `shareTitle` varchar(200) NOT NULL,
                                      `layoutColor` varchar(10) NOT NULL,
                                      `playStatus` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否开启直播',
                                      `playbillType` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '节目单状态1自动2自定义',
                                      `lssPublishUrl` varchar(255) DEFAULT NULL,
                                      `isVr` int(1) NOT NULL DEFAULT '0',
                                      PRIMARY KEY (`id`),
                                      KEY `uin` (`uin`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1000040 DEFAULT CHARSET=utf8 COMMENT='电视频道';

CREATE TABLE `program_radio_channel` (
                                         `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                                         `name` varchar(180) NOT NULL DEFAULT '' COMMENT '名称',
                                         `introduce` varchar(50) NOT NULL DEFAULT '' COMMENT '简介',
                                         `logo` varchar(50) NOT NULL COMMENT '聚合页logo',
                                         `flowType` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '推流类型1视频2音频',
                                         `audioCover` varchar(50) NOT NULL DEFAULT '' COMMENT '纯音频封底图',
                                         `mpsLssAppId` varchar(20) NOT NULL DEFAULT '' COMMENT '播放器实例id',
                                         `mpsDynamicVodAppId` varchar(20) NOT NULL DEFAULT '' COMMENT 'mps 动态点播实例id',
                                         `mpsBackground` varchar(64) NOT NULL,
                                         `status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '状态1正常2回收站',
                                         `uin` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '操作人',
                                         `childId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '子账号id-0主账号',
                                         `aid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '频道id',
                                         `playlistsStatus` tinyint(1) unsigned NOT NULL DEFAULT '2' COMMENT 'µã²¥Ä£°å×´Ì¬1ÆôÓÃ2¹Ø±Õ',
                                         `playlistsId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'µã²¥Ä£°åid',
                                         `createTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
                                         `updateTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '修改时间',
                                         `publishTaskId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '·¢²¼ÈÎÎñid',
                                         `publishTaskMakeAppId` varchar(20) NOT NULL DEFAULT '' COMMENT '·¢²¼ÈÎÎñ°ó¶¨µÄÖÆ×÷µ¼²¥Ì¨ÊµÀýid',
                                         `pullUrl` varchar(1000) NOT NULL DEFAULT '' COMMENT 'À­Á÷µØÖ·',
                                         `pullStatus` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'À­Á÷µØÖ·ÊÇ·ñÆôÓÃ£¨0¹Ø±Õ£¬1ÆôÓÃ£©',
                                         `chatAuthModel` tinyint(1) unsigned NOT NULL DEFAULT '2' COMMENT 'ÁÄÌìÉóºËÀàÐÍ1£ºÖðÌõÉóºË2Ãô¸ÐÉóºË3×Ô¶¯¹ýÂË',
                                         `chatSee` tinyint(1) NOT NULL DEFAULT '1',
                                         `chatLogin` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'ÁÄÌìÊÇ·ñÐèÒªµÇÂ¼£¬1ÐèÒª0²»ÐèÒª',
                                         `chatAdminName` varchar(20) NOT NULL DEFAULT '' COMMENT 'ÁÄÌì¹ÜÀíÔ±Ãû',
                                         `chatAdminAva` varchar(64) NOT NULL DEFAULT '' COMMENT 'ÁÄÌì¹ÜÀíÔ±Í·Ïñ',
                                         `defaultUserAva` varchar(64) NOT NULL DEFAULT '',
                                         `pullStream` int(1) unsigned NOT NULL DEFAULT '0' COMMENT 'ÊÇ·ñ½øÐÐÀ­Á÷ 1ÊÇ 0·ñ',
                                         `lssApp` varchar(64) NOT NULL DEFAULT '' COMMENT 'lss APP',
                                         `stream` varchar(64) NOT NULL DEFAULT '' COMMENT '流stream',
                                         `streamType` tinyint(1) unsigned NOT NULL DEFAULT '1',
                                         `watchNum` int(10) NOT NULL DEFAULT '0' COMMENT '观看数量',
                                         `isDisplayWatchNum` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否展示观看量1是2否',
                                         `customWatchStatus` tinyint(1) NOT NULL DEFAULT '2' COMMENT '是否开启自定义观看数据，2否1是',
                                         `shareImg` varchar(64) DEFAULT NULL,
                                         `shareSubTitle` varchar(200) NOT NULL,
                                         `shareTitle` varchar(200) NOT NULL,
                                         `layoutColor` varchar(10) NOT NULL,
                                         `playStatus` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否开启直播',
                                         `lssPublishUrl` varchar(255) DEFAULT NULL,
                                         `playbillType` tinyint(1) NOT NULL DEFAULT '0' COMMENT '节目单 0为默认1为自定义',
                                         PRIMARY KEY (`id`),
                                         KEY `uin` (`uin`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1000017 DEFAULT CHARSET=utf8 COMMENT='电台频道';

CREATE TABLE `user` (
                        `uin` int(10) unsigned NOT NULL AUTO_INCREMENT,
                        `password` char(32) NOT NULL COMMENT '密码',
                        `realName` varchar(50) NOT NULL COMMENT '真实姓名',
                        `company` varchar(50) NOT NULL DEFAULT '' COMMENT 'µ¥Î»',
                        `specialRoomType` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '1特殊域名对接2一般特殊对接',
                        `ava` varchar(200) NOT NULL COMMENT '头像',
                        `aodianUin` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '奥点云用户id',
                        `aodianAccessId` varchar(64) NOT NULL COMMENT '奥点云access id',
                        `aodianAccessKey` varchar(64) NOT NULL COMMENT '奥点云access key',
                        `aodianUinPStream` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '°ÂµãÔÆÓÃ»§À­Á÷id',
                        `aodianAccessIdPStream` varchar(64) NOT NULL DEFAULT '' COMMENT '°ÂµãÔÆÀ­Á÷access id',
                        `aodianAccessKeyPStream` varchar(64) NOT NULL DEFAULT '' COMMENT '°ÂµãÔÆÀ­Á÷access key',
                        `lssApp` varchar(64) NOT NULL,
                        `lssAppPStream` varchar(64) NOT NULL DEFAULT '',
                        `lpsApp` varchar(64) NOT NULL,
                        `broadcastMakeHsmsGroupId` varchar(64) NOT NULL COMMENT '制作场景组ID',
                        `authStatus` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '实名认证状态，0未认证，1认证',
                        `registerTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '注册时间',
                        `lastLoginTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最后登录时间',
                        `lcpsUsedTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '累积使用时间',
                        `accountStatus` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '账户状态，1正常',
                        `dmsKeyInfo` varchar(500) NOT NULL COMMENT 'dms key json信息',
                        `msgDmsKey` varchar(500) NOT NULL COMMENT '消息dms',
                        `userType` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '用户分类',
                        `userFrom` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '用户来源1商务客户2代理商客户',
                        `broadcastMakeType` tinyint(1) unsigned NOT NULL DEFAULT '2' COMMENT '制作导播台信源数类型，1：5个，2：4个',
                        `liveProgramMpsId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '活动直播播放器ID',
                        `tvProgramMpsId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '电视直播播放器id',
                        `radioProgramMpsId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '电台直播播放器',
                        `businessManagerId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '对接商务经理id',
                        `status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '×´Ì¬1ÆôÓÃ2½ûÓÃ',
                        `maxrecordduration` int(2) unsigned NOT NULL DEFAULT '1' COMMENT 'Ã½×Ê×î´ó´æ´¢Ê±¼ä',
                        `newsTitle` varchar(255) NOT NULL DEFAULT '' COMMENT 'ÐÂÎÅÒ³Ãæ×Ô¶¨Òåtitle',
                        `rbacStatus` tinyint(1) unsigned NOT NULL DEFAULT '0',
                        `isExamine` tinyint(1) NOT NULL DEFAULT '0',
                        `leagueStatus` tinyint(1) NOT NULL DEFAULT '0',
                        `cname` varchar(255) NOT NULL DEFAULT '',
                        `cnameStatus` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'cname https 0¹Ø±Õ1ÆôÓÃ',
                        `agencyLoginBackground` varchar(50) NOT NULL DEFAULT '' COMMENT '登录页背景图',
                        `tvLssApp` varchar(64) NOT NULL DEFAULT '' COMMENT '电视电台lss app',
                        `copyLssApp` varchar(64) NOT NULL DEFAULT '' COMMENT '直播间复制拉流lss app',
                        `cmsExamine` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'cms直播审核，开启1，关闭0',
                        `tvStorage` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '电视直播是否存储1是2否',
                        `radioStorage` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '电台直播是否存储1是2否',
                        `projectVersion` tinyint(1) unsigned NOT NULL DEFAULT '1',
                        `liveVersion` tinyint(1) unsigned NOT NULL DEFAULT '1',
                        `authKey` varchar(30) NOT NULL DEFAULT '' COMMENT '认证口令',
                        `roleInit` tinyint(1) NOT NULL DEFAULT '0' COMMENT '角色列表初始化标志',
                        `twAuditing` tinyint(1) NOT NULL DEFAULT '1' COMMENT '图文直播审核开关  1开0关',
                        `clientStore` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否开启连麦导播存储',
                        `version` varchar(10) NOT NULL DEFAULT 'produce' COMMENT 'produce为正式pre为灰度',
                        `platform` varchar(30) NOT NULL DEFAULT 'gdy' COMMENT '平台',
                        `userId` varchar(40) DEFAULT '0' COMMENT '平台唯一Id',
                        `domainConfig` varchar(255) NOT NULL COMMENT '域名防盗链配置',
                        `demandReferStatus` tinyint(3) unsigned NOT NULL DEFAULT '2' COMMENT '点播防盗链状态，1开启，2关闭',
                        PRIMARY KEY (`uin`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=10000036 DEFAULT CHARSET=utf8;


CREATE TABLE `mss_media_library` (
                         `mssId` int(10) unsigned NOT NULL AUTO_INCREMENT,
                         `title` varchar(32) NOT NULL DEFAULT '',
                         `url` varchar(2000) NOT NULL DEFAULT '' COMMENT '播放地址',
                         `duration` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '视频的时长',
                         `thumbnail` varchar(2000) NOT NULL DEFAULT '' COMMENT '视频的封面图',
                         PRIMARY KEY (`mssId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='媒资库';
